version: "2"
services:

  metabase-postgres-db:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    volumes:
      - 'postgresql_mb_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=mb_user
      - POSTGRESQL_PASSWORD=mb_password
      - POSTGRESQL_DATABASE=mb_database
      - POSTGRESQL_POSTGRES_PASSWORD=xpostgres 

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    #volumes:
      # declare your mount volume /host/dir:/container/dir
      #- /home/app/metabase-data:/metabase-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=mb_database
      - MB_DB_PORT=5432
      - MB_DB_USER=mb_user
      - MB_DB_PASS=mb_password
      - MB_DB_HOST=metabase-postgres-db
    depends_on:
      - metabase-postgres-db
    links:
      - metabase-postgres-db
volumes:
  postgresql_mb_data:      